import { describe, expect, it } from "vitest";
import { VERIFY_COMMAND_RE } from "@/lib/telegram";

function parseCode(text: string): string | null {
  const m = text.match(VERIFY_COMMAND_RE);
  return m ? m[1].toUpperCase() : null;
}

describe("VERIFY_COMMAND_RE", () => {
  it("matches /verify CODE", () => {
    expect(parseCode("/verify ABC234")).toBe("ABC234");
  });

  it("matches /start CODE (deeplink)", () => {
    expect(parseCode("/start ABC234")).toBe("ABC234");
  });

  it("matches case-insensitively but normalizes to uppercase", () => {
    expect(parseCode("/VERIFY abc234")).toBe("ABC234");
    expect(parseCode("/Verify Abc234")).toBe("ABC234");
  });

  it("tolerates @botname suffix on the command", () => {
    expect(parseCode("/verify@pingup_alerts_bot ABC234")).toBe("ABC234");
    expect(parseCode("/start@PingupBot ABC234")).toBe("ABC234");
  });

  it("rejects codes that aren't exactly 6 chars long", () => {
    expect(parseCode("/verify ABCDE")).toBeNull(); // 5 chars
    expect(parseCode("/verify ABCDEFG")).toBeNull(); // 7 chars, \b boundary fails
    expect(parseCode("/verify abc0de")).toBeNull(); // contains 0 (not in [A-Z2-9])
  });

  it("does not enforce the verification alphabet at the regex level", () => {
    // O, I, 1 aren't generated by us, but the regex still accepts them — the
    // DB lookup downstream just won't find a match, which is harmless.
    expect(parseCode("/verify abcOde")).toBe("ABCODE");
    expect(parseCode("/verify ABCDEI")).toBe("ABCDEI");
  });

  it("ignores other commands", () => {
    expect(parseCode("/help")).toBeNull();
    expect(parseCode("/foo BARBAZ")).toBeNull();
    expect(parseCode("hello")).toBeNull();
  });
});
